version: "2"
services:
    redis:
        container_name: redis
        image: redis
        ports:
            - "6379:6379" 
        restart: always
    
    mysql:
      container_name: mysql
      image: mariadb:10.5
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - "3308:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: restaurant
        MYSQL_HOST: 127.0.0.1

    flask:
        container_name: flask
        build: 
          context: ../
          dockerfile: Dockerfile
        depends_on:
          - redis
          - mysql
        command: supervisord -n 
        env_file: tripadvisor.env
        expose:
            - "8700"
            - "3306"
        ports:
            - "8700:8700"
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        restart: always

    nginx:
      container_name: nginx
      build:
        context: ../
        dockerfile: docker_nginx
      command: 
          nginx -g 'daemon off;' 
      depends_on:
        - flask
      ports:
        - "80:80"
      logging:
        driver: "json-file"
        options:
            max-size: "50m"

      volumes:
        - ./nginx/nginx.conf:/etc/nginx/sites-enabled/nginx.conf
        - ./nginx/site_enabled/default.conf:/etc/nginx/conf.d/default.conf
      restart: always