version: "2"
services:
    redis:
        container_name: redis
        image: redis
        ports:
            - "6379:6379" 
        restart: always

    flask:
        container_name: flask
        build: 
          context: ../
          dockerfile: Dockerfile
        depends_on:
          - redis
        command: supervisord -n
        env_file: tripadvisor.env
        expose:
            - "8700"
        ports:
            - "8700:8700"
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        restart: always

    nginx:
      container_name: nginx
      build:
        context: ../
        dockerfile: docker_nginx
      command: 
          nginx -g 'daemon off;' 
      depends_on:
        - flask
      ports:
        - "80:80"
      logging:
        driver: "json-file"
        options:
            max-size: "50m"

      volumes:
        - ./nginx/nginx.conf:/etc/nginx/sites-enabled/nginx.conf
        - ./nginx/site_enabled/default.conf:/etc/nginx/conf.d/default.conf
      restart: always